services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "${MC_VERSION}"
      MEMORY: "${MC_MEMORY}"
      LEVEL: "${MC_WORLD_NAME}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      CREATE_CONSOLE_IN_PIPE: "true"
      ENABLE_RCON: "${ENABLE_RCON}"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: "${RCRON_PORT}"
    volumes:
      # Maps the host directory from .env to the container's /data
      - ${MC_DATA_DIR}:/data
    ports:
      - "${PORTS}"
    restart: unless-stopped

  backup:
    image: itzg/mc-backup
    container_name: mc-backup
    environment:
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_HOST: mc
      BACKUP_METHOD: "tar"
      BACKUP_INTERVAL: "0 0 * * *"
      INITIAL_DELAY: "2m"
    volumes:
      - ${MC_DATA_DIR}:/data:ro
      - ${MC_BACKUP_DIR}:/backups
    depends_on:
      - mc
    restart: unless-stopped